import Header from "@/components/Header";

export const metadata = {
  title: "project-demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="min-h-screen">
            {children}
        </main>
      </body>
    </html>
  );
}
