import HeaderWrapper from "@/components/HeaderWrapper";

export const metadata = {
  title: "project-demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <HeaderWrapper />
      <main className="min-h-screen">
        {children}
      </main>
      <div id="portal-root" />
    </>
  );
}
